services:
  keycloak:
    command: start-dev --import-realm
    image: "${KEYCLOAK_IMAGE}:${KEYCLOAK_VERSION}"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 8081:8080
    volumes:
      - ./config:/opt/keycloak/data/import
  postgres:
    image: "${POSTGRES_IMAGE}:${POSTGRES_VERSION}"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: preferences
  jaeger:
    image: "${JAEGER_IMAGE}:${JAEGER_VERSION}"
    ports:
      - '9411:9411'
      - '5778:5778'
      - '4318:4318'
      - '4317:4317'
      - '16686:16686'
