//go:build go1.22

// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package model

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Preferences defines model for Preferences.
type Preferences struct {
	Properties map[string]interface{} `json:"properties"`
}

// Problem defines model for Problem.
type Problem struct {
	// Detail A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem, e.g. by adding a fragment identifier or sub-path to the problem type. May be used to locate the root of this problem in the source code.
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status *int32 `json:"status,omitempty"`

	// Title A short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	Title *string `json:"title,omitempty"`

	// Type A URI reference that uniquely identifies the problem type only in the context of the provided API. Opposed to the specification in RFC-7807, it is neither recommended to be dereferencable and point to a human-readable documentation nor globally unique for the problem type.
	Type *string `json:"type,omitempty"`
}

// BadGateway defines model for BadGateway.
type BadGateway = Problem

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// Conflict defines model for Conflict.
type Conflict = Problem

// Forbidden defines model for Forbidden.
type Forbidden = Problem

// InternalServerError defines model for InternalServerError.
type InternalServerError = Problem

// NotAllowed defines model for NotAllowed.
type NotAllowed = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// SavePreferencesJSONRequestBody defines body for SavePreferences for application/json ContentType.
type SavePreferencesJSONRequestBody = Preferences

// UpdatePreferencesJSONRequestBody defines body for UpdatePreferences for application/json ContentType.
type UpdatePreferencesJSONRequestBody = Preferences

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get user preferences
	// (GET /v1/preferences)
	GetPreferences(w http.ResponseWriter, r *http.Request)
	// Save user preferences
	// (POST /v1/preferences)
	SavePreferences(w http.ResponseWriter, r *http.Request)
	// Update user preferences
	// (PUT /v1/preferences)
	UpdatePreferences(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetPreferences operation middleware
func (siw *ServerInterfaceWrapper) GetPreferences(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPreferences(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SavePreferences operation middleware
func (siw *ServerInterfaceWrapper) SavePreferences(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SavePreferences(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePreferences operation middleware
func (siw *ServerInterfaceWrapper) UpdatePreferences(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePreferences(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/preferences", wrapper.GetPreferences)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/preferences", wrapper.SavePreferences)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/preferences", wrapper.UpdatePreferences)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FdNcxM5E/4rXeK9veOPEFiWuQWKsNktQiokxYHNQR61PQJN9yC1TLzU/PctjWzHThwIh/XugZtlqdWP",
	"nn76Y76qipuWCUmCKr8qj6FlCtgvXmjzWgt+0Yu0qpgESdJP3bbOVlos06j1PHHY/P9jYEp7oaqx0enX",
	"/zxOVakejW5cjPJuGJ1lK9V1XaEMhsrbNl2nyuQVVm67Ii3P8XPEIPsE8WQ8LiEhWfnuCvWSaepstWcc",
	"z0tYO+4Kdcx+Yo1B2i+KwxJuPHeFOiFBT9q9Qz9H/8p79vsEtHIP2T9kAF2hTlmOnOMvaPbLz9MS3qDU",
	"bOCUBVYQMqBjjrRnOE/KHkf23BXqknSUmr39a9/EHJSw5TydWRqme888TtEjVbnitJ5b9GJ3rWTRoioV",
	"Tz5iSoWuUB4/R+vTiz5snr0qbp8t1ArjnVsNirYu/9pEfgR1bDSBR230xCHgdes09TxBaLGyU1uBMEht",
	"A3BVRd8/A3gKUiMsqQSptYANUKNrp9ElC8eVFtw6pcnAzM4RtJnbdAlBzV/S4dZzhWiG8N5bESSwBK9o",
	"5myoe6s1vil7QJpZQvShgBiidm4BxAIhWkHTnyAmEKxqspV2EER/wpqdQR/629LpBM+lWA3/JFUovNZN",
	"6xKbL5kIq54AYTBa9EQHBLENGuAoas17EG9plni3FERThbsIvjw/gXX4l0QZJLFTi6GnZ83zvfwWgMPZ",
	"ECYL0MZYmoGGqdezBmnjMg/sIcTJoNVS55htBGjR4hDe6AVMEGJAcytEnlmyUxvWRpYyPo6+QqjY4G2y",
	"Vrk0qtasDTBVqUfCn5AGlqY8SMEb9PwNMn9T9o0WVaro7WDNzS5ig2iJ4S6tFzXCbxcXZ5AP9NhghoRe",
	"Jw1MFj1w9nZmCUKunkkY35bxrdc9HR+mVeVisHN8o69tExtVio+48QZLcvhYFapZ7f8yHheqsZRXB2m1",
	"fJclwRn2FVysuJ1yCTX7pOWm0X5xJ836KP77OZL6UUrgS9JzbV3yuit6+Y/0xqmOLpGlJxylnDhNn1Tx",
	"kFSJZD9HdIvbObPJCDClA1msfc2/lg3m5taggaOzkyG8bVtean8z8XK5swTnxy8Hz34dPyvA9uWM0EqN",
	"HjxW3DRIJttOEAyugPaUJ8ZatiRpW+eiOlgHxHAVU65mP8QeZo4nfVDy+5bavBXoh+baD2RUV+xoMAGr",
	"6K0s3qWGlfvFBLVHfxSlvlkdr3z8/v5CLdtbuinv3viqRdrcJVP2r/qwzhMl6d7m7enRmbrTR8/Yi3Zw",
	"+ho2G+Y6We7dn6MP+YaD4UG6llsk3VpVqsPheJiyM9XE/mWj+cGo3W7HM5S7mXiOEj2FVCs9tFvuUmPt",
	"Q3liVKleo2yj2fq4eDwef2MS+dEJ5MbNjink7R/p6U+yw133rIGNNr42epOD75tsjzfJ6PD7RlvD9NOH",
	"INs1cfe2jx/0qvUXVZJ1rqE5RLviKHoW8lB18+9VV6iWww5BvNNz/L4a0qnbcuiJfsFm8c8p4WZGTN2p",
	"+ynC/54I79PPvSqMO0R42Rot+ICqlA/+VOJPJd5VYtbGw7W4OSOo8sP2dPDhqrtK2wlf6Hejd8spoByN",
	"+hGy5iDl8/H4QKWzSyfrWWDTWXfV/R0AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
