server:
  port: 9001
  address: 0.0.0.0

spring:
  application:
    name: preferences
  jackson:
    serialization:
      # needed for serializing objects of type object
      fail-on-empty-beans: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs #Keycloak Endpoint
  datasource:
    url: jdbc:postgresql://${PREFERENCES_DB_HOST}:${PREFERENCES_DB_PORT}/${PREFERENCES_DB}
    username: ${PREFERENCES_DB_USERNAME}
    password: ${PREFERENCES_DB_PASSWORD}
  jpa:
    database: postgresql
    properties:
      hibernate:
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 100
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: "classpath:/db/changelog.xml"

preferences:
  realm: ${KEYCLOAK_REALM}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # sample every request
  zipkin:
    tracing:
      endpoint: http://${COLLECTOR_HOST}:${COLLECTOR_PORT}/api/v2/spans

logger:
  traceIdHeaderName: ${TRACE_ID_HEADER_NAME}
  enabled: true
  excludePaths:
    - "/actuator/**"

logging:
  structured:
    format:
      console: logstash
  level:
    root: info
