spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/ONAP/protocol/openid-connect/certs #Keycloak Endpoint
  datasource:
    url: jdbc:postgresql://localhost:5432/preferences
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 100
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: "classpath:/db/changelog.xml"

preferences:
    realm: ONAP

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
