server:
    port: 9001
    address: 0.0.0.0

spring:
  application:
    name: preferences
  jackson:
    serialization:
      # needed for serializing objects of type object
      FAIL_ON_EMPTY_BEANS: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs #Keycloak Endpoint
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}

preferences:
    realm: ${KEYCLOAK_REALM}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # sample every request
  zipkin:
    tracing:
      endpoint: http://${COLLECTOR_HOST}:${COLLECTOR_PORT}/api/v2/spans

logger:
  traceIdHeaderName: "X-Request-Id"
  enabled: true
  excludePaths:
    - "/actuator/**"