server:
    port: 9001
    address: 0.0.0.0

spring:
  jackson:
    serialization:
      # needed for serializing objects of type object
      FAIL_ON_EMPTY_BEANS: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/ONAP/protocol/openid-connect/certs #Keycloak Endpoint
  data:
    mongodb:
      database: portal_prefs
      host: localhost
      port: 27017
      username: root
      password: password

portal-prefs:
    realm: ONAP

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
