spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/ONAP/protocol/openid-connect/certs #Keycloak Endpoint
  datasource:
    url: jdbc:postgresql://localhost:5432/preferences
    username: postgres
    password: postgres
  jpa:
    show-sql: true

preferences:
    realm: ONAP

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logger:
  traceIdHeaderName: x-b3-traceid
